---
- hosts: all
  become: true
  
  tasks:
    - name: symlink /usr/bin/python -> /usr/bin/python3
      raw: |
        if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python3 /usr/bin/python; 
        fi
      become: true

    - debug: var=ansible_host

    - import_role:
       name: phaustin.proxy.docker


