---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'curl', 'python3', 'python3-dev', 'python3-pip']

    - name: Download the TLJH installer
      get_url:
        url: "{{ tljh_installer_url }}"
        dest: "{{ tljh_installer_dest }}"

    - name: Run the TLJH installer
      shell: |
        {{ ansible_python_interpreter }}  {{ tljh_installer_dest }} --admin jovyan

    - name: Set the idle culler timeout to 1 hour
      shell: "tljh-config set services.cull.timeout 3600"

    - name: Set the default memory and cpu limits
      shell: |
        tljh-config set limits.memory 2G
        tljh-config set limits.cpu 2

    - name: Reload the hub
      shell: "tljh-config reload hub"

